version: '3.7'

services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile-a
    ports:
      - "3000:3000"
    depends_on:
      - service-b
      - zipkin
      - otel-collector

  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile-b
    ports:
      - "3001:3001"
    depends_on:
      - zipkin
      - otel-collector

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"  # gRPC
      - "4318:4318" # HTTP
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    command: ["--config", "/etc/otel-local-config.yaml"]
