# Usando a imagem base do Go
FROM golang:1.23 AS builder

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando o código fonte para o contêiner
COPY service-a/go.mod service-a/go.sum ./
RUN go mod download

COPY service-a/ .

# Compilando a aplicação
RUN go build -o service-a .

# O contêiner final
FROM gcr.io/distroless/base
WORKDIR /app
COPY --from=builder /app/service-a /app/
CMD ["/app/service-a"]